lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    user_identity_field: "username"
    token_ttl: '%env(int:JWT_TOKEN_TTL)%'
#    encoder:
#        service: app.jwt_authentication.encoder
#    token_extractors:
#        authorization_header:
#            prefix:   "%jwt_token_authorization_header_prefix%"