api_login:
  path: /authenticate
  methods: [POST]

gesdinet_jwt_refresh_token:
  path:     /token/refresh
  controller: gesdinet.jwtrefreshtoken:refresh
  methods: [POST]

authentication_logout:
  path:     /logout
  controller: EasyApiJwtAuthentication\Controller\AuthenticationController::logoutAction
  methods: [POST]
